<h2>Syntax</h2>

<pre>
	<code>try($tryFunc, $catchFunc)</code>
</pre>

<h2>Description</h2>

<div>
<div>Executes a try function and handles any errors that occur using a catch function. The try function implements a try-catch behavior for TLScript that enables robust error handling.</div>
</div>

<p>The function works with two parameters:</p>

<ol>
	<li><strong>Try function</strong>: The function to be executed that could cause an error</li>
	<li><strong>Catch function</strong>: The fallback function that is executed in the event of an error</li>
</ol>

<div>
<div>If the try function is executed successfully, its result is returned. If an error occurs, the catch function is executed with specific parameters:</div>

<ul>
	<li><strong>I18NException</strong>: catch function receives (ResKey, original argument)</li>
	<li><strong>Regular exception</strong>: catch function receives (error message, original argument)</li>
</ul>
</div>

<h2>Parameters</h2>

<table class="tlDocTable" style="height:155px; width:1517px">
	<thead>
		<tr>
			<th>Name</th>
			<th>Type</th>
			<th>Type Description</th>
			<th>Mandatory</th>
			<th>Standard</th>
		</tr>
		<tr>
			<td>
			<p>tryFunc</p>
			</td>
			<td>Function</td>
			<td>The function that is to be executed.</td>
			<td>yes</td>
			<td>-</td>
		</tr>
		<tr>
			<td>catchFunc</td>
			<td>Function</td>
			<td>The fallback function that is executed in the event of an error. Receives the exception object as a parameter</td>
			<td>no</td>
			<td>null</td>
		</tr>
	</thead>
</table>

<h2>Return value</h2>

<p><strong>Type:</strong> Object</p>

<div>
<div>Returns the result of the try function if it was executed successfully. If an error occurs, the result of the catch function is returned. If no catch function is specified, <code class="hljs inlineCode">null</code>is returned in the event of an error.</div>
</div>

<h2>Examples</h2>

<pre>
	<code>try(
  sendMail(
    subject: $subject,
    to: $emailAddr,
    body: $emailBody
  ),
  catchFun: mailError -&gt; {
    info("E-Mail-Zustellung an " + $emailAddr + " fehlgeschlagen. Grund: " + $mailError);
    false
  }
)</code>
</pre>

<p><strong>Output: </strong>Attempts to send an e-mail. If successful, the result of <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">sendMail</code> is returned. If an error occurs, <code class="bg-text-200/5 border border-0.5 border-border-300 text-danger-000 whitespace-pre-wrap rounded-[0.4rem] px-1 py-px text-[0.9rem]">false</code> is returned and a user info with the attempted e-mail address.</p>
